name: 'example'
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  matrix_input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: array
        with:
          cmd: ls src
    outputs:
      param: ${{ steps.array.outputs.build }}
  dynamic_matrix:
    needs:
      - matrix_input
    strategy:
      matrix:
        param: ${{ fromJson(needs.matrix_input.outputs.param) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.param }}
