name: 'test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: newline
        with:
          str: |
            a
            b
            c
      - run: |
          test '${{ steps.newline.outputs.build }}' = '["a","b","c"]'
      - uses: ./
        id: space
        with:
          str: a b c
          separator: 'space'
      - run: |
          test '${{ steps.space.outputs.build }}' = '["a","b","c"]'
      - uses: ./
        id: csv
        with:
          str: a,b,c
          separator: ','
      - run: |
          test '${{ steps.csv.outputs.build }}' = '["a","b","c"]'
      - uses: ./
        id: append
        with:
          str: d
          append_to: ${{ steps.newline.outputs.build }}
      - run: |
          test '${{ steps.append.outputs.build }}' = '["a","b","c","d"]'
